-- NOTE: superseded same day. Caliber-derived transfers reverted from per-call back to phone+ET-day
-- (source-prefixed), matching the phone/day CCO. Final state applied live via MCP =
-- derive_transfer_caliber_phone_day_restore. conversion_call_id stored as identifier only.
